name: Deploy API to Fly.io

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - 'public/data/conversions.json'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Copy conversion data to API directory
        run: cp public/data/conversions.json api/

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: ./api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}